In [1]:
import pandas as pd
import ast

In [2]:
ml_path = "../CineIq_Data/ml-25m/"
tmdb_path = "../CineIq_Data/tmdb-45k/"

In [3]:
ml_movies = pd.read_csv(ml_path + "movies.csv",)
ml_links = pd.read_csv(ml_path + "links.csv")

ml_merged = pd.merge(ml_movies,ml_links,on="movieId")
ml_merged = ml_merged.dropna(subset=["tmdbId"])
ml_merged["tmdbId"] = ml_merged["tmdbId"].astype(int)

In [4]:
ml_merged.columns

Index(['movieId', 'title', 'genres', 'imdbId', 'tmdbId'], dtype='str')

In [5]:
ml_merged.describe()

             movieId        imdbId         tmdbId
count   62316.000000  6.231600e+04   62316.000000
mean   122292.898774  1.457104e+06  155186.689999
std     63261.366338  2.098625e+06  153362.694700
min         1.000000  1.000000e+00       2.000000
25%     82233.000000  8.161050e+04   36768.750000
50%    138139.000000  3.256680e+05   86750.500000
75%    173267.500000  2.064717e+06  255255.250000
max    209171.000000  1.117094e+07  646282.000000

In [6]:
ml_merged.head()

,movieId,title,genres,imdbId,tmdbId
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,8844
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,15602
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,31357
4,5,Father of the Bride Part II (1995),Comedy,113041,11862

In [7]:
tmdb_meta = pd.read_csv(tmdb_path + "movies_metadata.csv",low_memory=False)
tmdb_meta["id"] = pd.to_numeric(tmdb_meta["id"],errors="coerce")
tmdb_meta = tmdb_meta.dropna(subset=["id"])
tmdb_meta["id"] = tmdb_meta["id"].astype(int)

In [8]:
tmdb_keywords = pd.read_csv(tmdb_path + "keywords.csv")
tmdb_keywords["id"] = pd.to_numeric(tmdb_keywords["id"],errors="coerce")
tmdb_keywords = tmdb_keywords.dropna(subset=["id"])
tmdb_keywords["id"] = tmdb_keywords["id"].astype(int)

In [9]:
tmdb_meta.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [10]:
tmdb_meta.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [11]:
tmdb_keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [12]:
base_df = pd.merge(ml_merged, tmdb_meta, left_on="tmdbId",right_on="id",how="inner")
final_df = pd.merge(base_df, tmdb_keywords, on="id",how="inner")

In [13]:
final_df.columns

Index(['movieId', 'title_x', 'genres_x', 'imdbId', 'tmdbId', 'adult',
       'belongs_to_collection', 'budget', 'genres_y', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_y', 'video',
       'vote_average', 'vote_count', 'keywords'],
      dtype='str')

In [14]:
required_columns = ["movieId","title_x","genres_y","overview","keywords"]
cineiq_df = final_df[required_columns].rename(columns={
    "title_x": "title",
    "genres_y": "tmdb_genres",
    "keywords": "tmdb_keywords",
    "overview": "tmdb_overview"
})

In [15]:
cineiq_df.head()

,movieId,title,tmdb_genres,tmdb_overview,tmdb_keywords
0,1,Toy Story (1995),"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,2,Jumanji (1995),"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,"[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,3,Grumpier Old Men (1995),"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,4,Waiting to Exhale (1995),"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,5,Father of the Bride Part II (1995),"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [16]:
def extract_names(x):
    if(pd.isna(x)):
        return ""
    try:
        data = ast.literal_eval(x)
        if isinstance(data,list):
            return " ".join([i["name"] for i in data])
    except:
        pass
    return ""

In [17]:
cineiq_df["genres"] = cineiq_df["tmdb_genres"].apply(extract_names)
cineiq_df["keywords"] = cineiq_df["tmdb_keywords"].apply(extract_names)
cineiq_df["overview"] = cineiq_df["tmdb_overview"].fillna('')

In [18]:
cineiq_df = cineiq_df[["movieId","title","overview","genres","keywords"]]

In [19]:
cineiq_df.head()

,movieId,title,overview,genres,keywords
0,1,Toy Story (1995),"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,jealousy toy boy friendship friends rivalry bo...
1,2,Jumanji (1995),When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,board game disappearance based on children's b...
2,3,Grumpier Old Men (1995),A family wedding reignites the ancient feud be...,Romance Comedy,fishing best friend duringcreditsstinger old men
3,4,Waiting to Exhale (1995),"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,based on novel interracial relationship single...
4,5,Father of the Bride Part II (1995),Just when George Banks has recovered from his ...,Comedy,baby midlife crisis confidence aging daughter ...

In [20]:
output_path = "../CineIq_Data/modify/cineiq_metadata.csv"
cineiq_df.to_csv(output_path,index=False)